.class public LX/FEj;
.super Ljava/lang/Object;
.source ""


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:I

.field public A06:I

.field public A07:I

.field public A08:I

.field public A09:I

.field public A0A:I

.field public A0B:I

.field public A0C:I

.field public A0D:I

.field public A0E:I

.field public A0F:I

.field public A0G:J

.field public A0H:LX/GGo;

.field public A0I:LX/GGo;

.field public A0J:LX/GGr;

.field public A0K:LX/GGy;

.field public A0L:LX/GGs;

.field public A0M:LX/GGm;

.field public A0N:LX/GGq;

.field public A0O:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0P:LX/GGu;

.field public A0Q:LX/GGp;

.field public A0R:LX/GGl;

.field public A0S:LX/GGv;

.field public A0T:LX/GGv;

.field public A0U:LX/GGn;

.field public A0V:Ljava/lang/String;

.field public A0W:Ljava/util/HashMap;

.field public A0X:Ljava/util/Map;

.field public A0Y:Ljava/util/Set;

.field public A0Z:Ljava/util/Set;

.field public A0a:Ljava/util/Set;

.field public A0b:Ljava/util/Set;

.field public A0c:Ljava/util/Set;

.field public A0d:Ljava/util/Set;

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z

.field public A0m:Z


# direct methods
.method public constructor <init>()V
    .locals 7

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v1, 0x0

    sget-object v0, LX/GH0;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/FEj;->A0O:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    const/4 v2, 0x1

    iput-boolean v1, p0, LX/FEj;->A0f:Z

    const/4 v0, 0x3

    iput v0, p0, LX/FEj;->A07:I

    const/16 v3, 0x7d0

    const-string v0, "ExoService"

    iput-object v0, p0, LX/FEj;->A0V:Ljava/lang/String;

    const/16 v6, 0xfa

    iput-boolean v2, p0, LX/FEj;->A0l:Z

    new-instance v0, LX/F3g;

    invoke-direct {v0}, LX/F3g;-><init>()V

    iget-boolean v2, v0, LX/F3g;->A00:Z

    new-instance v0, LX/GGq;

    invoke-direct {v0, v2}, LX/GGq;-><init>(Z)V

    iput-object v0, p0, LX/FEj;->A0N:LX/GGq;

    const/16 v2, 0x3e8

    const/16 v5, 0x1f4

    new-instance v0, LX/GGv;

    invoke-direct {v0, v5, v3}, LX/GGv;-><init>(II)V

    iput-object v0, p0, LX/FEj;->A0S:LX/GGv;

    new-instance v0, LX/GGv;

    invoke-direct {v0, v1, v1}, LX/GGv;-><init>(II)V

    iput-object v0, p0, LX/FEj;->A0T:LX/GGv;

    new-instance v0, LX/GGu;

    invoke-direct {v0}, LX/GGu;-><init>()V

    iput-object v0, p0, LX/FEj;->A0P:LX/GGu;

    new-instance v0, LX/Erf;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    new-instance v0, LX/GGs;

    invoke-direct {v0}, LX/GGs;-><init>()V

    iput-object v0, p0, LX/FEj;->A0L:LX/GGs;

    sget-object v0, LX/GGy;->A00:LX/GGy;

    iput-object v0, p0, LX/FEj;->A0K:LX/GGy;

    new-instance v0, LX/ErZ;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    new-instance v0, LX/GGr;

    invoke-direct {v0}, LX/GGr;-><init>()V

    iput-object v0, p0, LX/FEj;->A0J:LX/GGr;

    new-instance v0, LX/Erg;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    new-instance v0, LX/GGm;

    invoke-direct {v0}, LX/GGm;-><init>()V

    iput-object v0, p0, LX/FEj;->A0M:LX/GGm;

    new-instance v0, LX/Eri;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    new-instance v0, LX/GGn;

    invoke-direct {v0}, LX/GGn;-><init>()V

    iput-object v0, p0, LX/FEj;->A0U:LX/GGn;

    new-instance v0, LX/GGl;

    invoke-direct {v0}, LX/GGl;-><init>()V

    iput-object v0, p0, LX/FEj;->A0R:LX/GGl;

    new-instance v4, LX/FB5;

    invoke-direct {v4}, Ljava/lang/Object;-><init>()V

    const v0, 0x186a0

    iput v0, v4, LX/FB5;->A00:I

    iput v2, v4, LX/FB5;->A03:I

    iput v5, v4, LX/FB5;->A02:I

    iput v6, v4, LX/FB5;->A01:I

    new-instance v0, LX/GGo;

    invoke-direct {v0, v4}, LX/GGo;-><init>(LX/FB5;)V

    iput-object v0, p0, LX/FEj;->A0H:LX/GGo;

    new-instance v4, LX/FB5;

    invoke-direct {v4}, Ljava/lang/Object;-><init>()V

    iput v3, v4, LX/FB5;->A00:I

    const v0, 0x249f0

    iput v0, v4, LX/FB5;->A03:I

    const v0, 0x86470

    iput v0, v4, LX/FB5;->A02:I

    const v0, 0x1e8480

    iput v0, v4, LX/FB5;->A01:I

    new-instance v0, LX/GGo;

    invoke-direct {v0, v4}, LX/GGo;-><init>(LX/FB5;)V

    iput-object v0, p0, LX/FEj;->A0I:LX/GGo;

    iput-boolean v1, p0, LX/FEj;->A0g:Z

    iput-boolean v1, p0, LX/FEj;->A0i:Z

    const/16 v6, 0xfa0

    invoke-static {}, LX/0mY;->A0x()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0W:Ljava/util/HashMap;

    const-wide/16 v4, 0x0

    iput-wide v4, p0, LX/FEj;->A0G:J

    invoke-static {}, LX/0mY;->A0x()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0X:Ljava/util/Map;

    const/16 v0, 0x7530

    iput v0, p0, LX/FEj;->A04:I

    const/4 v0, -0x1

    iput v0, p0, LX/FEj;->A0D:I

    iput v6, p0, LX/FEj;->A03:I

    invoke-static {}, LX/0mY;->A0y()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0b:Ljava/util/Set;

    invoke-static {}, LX/0mY;->A0y()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0a:Ljava/util/Set;

    invoke-static {}, LX/0mY;->A0y()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0c:Ljava/util/Set;

    new-instance v0, LX/GGp;

    invoke-direct {v0}, LX/GGp;-><init>()V

    iput-object v0, p0, LX/FEj;->A0Q:LX/GGp;

    invoke-static {}, LX/0mY;->A0y()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0Z:Ljava/util/Set;

    invoke-static {}, LX/0mY;->A0y()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0Y:Ljava/util/Set;

    invoke-static {}, LX/0mY;->A0y()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FEj;->A0d:Ljava/util/Set;

    const/16 v0, 0x28

    iput v0, p0, LX/FEj;->A0C:I

    iput v0, p0, LX/FEj;->A0B:I

    iput v1, p0, LX/FEj;->A08:I

    const/4 v0, -0x1

    iput v0, p0, LX/FEj;->A09:I

    iput v0, p0, LX/FEj;->A0E:I

    iput v2, p0, LX/FEj;->A06:I

    iput v3, p0, LX/FEj;->A05:I

    iput v2, p0, LX/FEj;->A00:I

    iput v2, p0, LX/FEj;->A02:I

    const v0, 0x8000

    iput v0, p0, LX/FEj;->A01:I

    iput-boolean v1, p0, LX/FEj;->A0h:Z

    iput-boolean v1, p0, LX/FEj;->A0e:Z

    const/16 v0, 0x18

    iput v0, p0, LX/FEj;->A0A:I

    iput-boolean v1, p0, LX/FEj;->A0m:Z

    const/4 v0, -0x1

    iput v0, p0, LX/FEj;->A0F:I

    return-void
.end method
